# Generated by Django 5.1.15 on 2026-09-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'código de verificación', 'verbose_name_plural': 'códigos de verificación'},
        ),
    ]
