# Generated by Django 5.1.15 on 2026-08-06 17:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('failure', models.CharField(blank=True, max_length=32, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='studies.study')),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='analysis_an_status_633cd3_idx')],
            },
        ),
    ]
