# Generated by Django 5.1.15 on 2026-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='signal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
