# Generated by Django 5.1.15 on 2026-09-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_signal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-requested_at'], 'verbose_name': 'análisis', 'verbose_name_plural': 'análisis'},
        ),
    ]
