# Generated by Django 5.1.15 on 2026-08-06 17:39

import django.db.models.deletion
import django.utils.timezone
import studies.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(max_length=24)),
                ('captured_at', models.DateTimeField()),
                ('mount', models.CharField(choices=[('standard-3x4', '3x4 standard'), ('rhythm-3x4', '3x4 with rhythm strip'), ('right-3x3', '3x3 right-sided'), ('six-2', '6x2'), ('twelve-1', '12x1')], default='standard-3x4', max_length=16)),
                ('speed_mm_per_second', models.FloatField(default=25.0)),
                ('gain_mm_per_millivolt', models.FloatField(default=10.0)),
                ('quad', models.JSONField()),
                ('image', models.ImageField(upload_to=studies.models.study_image_path)),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'studies',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['owner', '-received_at'], name='studies_stu_owner_i_0d435a_idx')],
            },
        ),
    ]
