# Generated by Django 5.1.15 on 2026-09-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-received_at'], 'verbose_name': 'estudio', 'verbose_name_plural': 'estudios'},
        ),
    ]
